language: node_js
node_js:
- 6
cache:
  yarn: true
  directories:
  - node_modules
script:
- npm run test-valid
- npm run test-invalid
env:
- ACCESS_ID=gitaclue
- ACCESS_TOKEN=ca72873ab79a7c8a53c768853d91b74bad1b62e9